<?php
/**
 * subsite.php — wildcard host renderer for *.yassota.com
 * ======================================================
 * Every generated subdomain shares this ONE file (via the wildcard
 * docroot). It reads the incoming Host header, finds the matching row
 * in `subsites`, and renders its AI/SEO content with the Syria-Home
 * theme. Apex + www fall through to the main app (index.php).
 *
 * Wire-up (in .htaccess or index.php front controller):
 *   if the host is a known subsite → include subsite.php.
 * A convenience router is provided at the bottom: yassota_maybe_subsite().
 */

require_once __DIR__ . '/partials.php';

function yassota_current_host(): string
{
    $h = strtolower($_SERVER['HTTP_HOST'] ?? '');
    return preg_replace('/:\d+$/', '', $h); // strip port
}

/** Is this host a generated subsite (not apex/www)? */
function yassota_is_subsite_host(string $host): bool
{
    $root = function_exists('setting') ? (string)setting('factory_root_domain') : '';
    if (!$root) $root = defined('SITE_URL') ? preg_replace('#^https?://(www\.)?#', '', rtrim(SITE_URL, '/')) : '';
    if (!$root) return false;
    if ($host === $root || $host === 'www.' . $root) return false;
    return str_ends_with($host, '.' . $root);
}

function yassota_find_subsite(string $host): ?array
{
    if (!function_exists('db')) return null;
    try {
        $row = db()->prepare('SELECT * FROM subsites WHERE host=? LIMIT 1');
        $row->execute([$host]);
        $r = $row->fetch();
        return $r ?: null;
    } catch (Throwable $e) { return null; }
}

/** Render a single subsite page and exit. */
function yassota_render_subsite(array $s): void
{
    // bump views (best-effort)
    if (function_exists('db')) { try { db()->prepare('UPDATE subsites SET views=views+1 WHERE id=?')->execute([$s['id']]); } catch (Throwable $e) {} }

    $base = (!empty($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $s['host'];
    $jsonld = json_encode([
        '@context' => 'https://schema.org',
        '@type' => 'Article',
        'headline' => $s['title'],
        'description' => $s['description'],
        'inLanguage' => $s['lang'] ?: 'ar',
        'url' => $base . '/',
        'datePublished' => date('c', strtotime($s['created_at'] ?? 'now')),
        'publisher' => ['@type' => 'Organization', 'name' => 'Yassota'],
    ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

    yassota_header([
        'title'       => $s['title'] . ' | Yassota',
        'description' => $s['description'],
        'canonical'   => $base . '/',
        'dir'         => ($s['lang'] ?? 'ar') === 'ar' ? 'rtl' : 'ltr',
        'jsonld'      => $jsonld,
    ]);
    ?>
    <div class="container">
      <article class="page-hero" style="padding-bottom:10px">
        <span class="eyebrow"><?= e(ucfirst($s['niche'])) ?></span>
        <h1><?= e($s['title']) ?></h1>
        <p class="lead"><?= e($s['description']) ?></p>
      </article>
      <div class="ad-zone" id="adTop"></div>
      <div class="tool-shell" style="line-height:1.9">
        <?= $s['html'] /* trusted: generated by our own factory */ ?>
      </div>
      <section class="section-head" style="margin-top:40px"><h2>أدوات مجانية قد تفيدك</h2><a class="more" href="https://<?= e(preg_replace('/^[^.]+\./', '', $s['host'])) ?>/tools.php">كل الأدوات ←</a></section>
      <p style="color:var(--muted)">استكشف أكثر من ٢٠٠ أداة ويب مجانية على شبكة Yassota.</p>
    </div>
    <?php
    yassota_footer();
    exit;
}

/**
 * Front-controller helper: call this at the very top of index.php.
 * If the host is a known subsite, it renders and exits; otherwise returns.
 */
function yassota_maybe_subsite(): void
{
    $host = yassota_current_host();
    if (!yassota_is_subsite_host($host)) return;
    $s = yassota_find_subsite($host);
    if ($s && !empty($s['html'])) {
        yassota_render_subsite($s); // exits
    }
    // Unknown subsite host: show a lightweight, indexable placeholder
    // (so the wildcard never returns a broken page to crawlers).
    yassota_header(['title' => 'Yassota Network', 'description' => 'صفحة قيد الإعداد على شبكة Yassota.']);
    echo '<div class="container"><div class="empty-state"><h1>قريبًا</h1><p>هذه الصفحة قيد الإعداد. تصفّح <a class="tag" href="/tools.php">أدواتنا المجانية</a> أو <a class="tag" href="/">الصفحة الرئيسية</a>.</p></div></div>';
    yassota_footer();
    exit;
}
