<?php
/**
 * tools_catalog.php — AUTO-GENERATED from assets/js/tools.js.
 * PHP mirror of tool metadata so every tool has a crawlable page.
 * Regenerate from tools.js; do not edit by hand. 201 tools.
 */
function yassota_tools_meta(): array {
  return [
    ['id' => 'word-counter', 'cat' => 'text', 'icon' => '📝', 'name' => 'Word Counter', 'desc' => 'Count words, characters, sentences and reading time.'],
    ['id' => 'case-converter', 'cat' => 'text', 'icon' => '🔠', 'name' => 'Case Converter', 'desc' => 'UPPER, lower, Title, Sentence, camelCase and more.'],
    ['id' => 'remove-duplicate-lines', 'cat' => 'text', 'icon' => '🧹', 'name' => 'Remove Duplicate Lines', 'desc' => 'Delete repeated lines, optionally case-insensitive.'],
    ['id' => 'sort-lines', 'cat' => 'text', 'icon' => '↕️', 'name' => 'Line Sorter', 'desc' => 'Sort lines alphabetically, reverse or by length.'],
    ['id' => 'find-replace', 'cat' => 'text', 'icon' => '🔁', 'name' => 'Find & Replace', 'desc' => 'Replace text with optional regex and case sensitivity.'],
    ['id' => 'reverse-text', 'cat' => 'text', 'icon' => '🪞', 'name' => 'Text Reverser', 'desc' => 'Reverse characters, words or lines.'],
    ['id' => 'text-repeater', 'cat' => 'text', 'icon' => '🔂', 'name' => 'Text Repeater', 'desc' => 'Repeat any text N times with a separator.'],
    ['id' => 'lorem-ipsum', 'cat' => 'text', 'icon' => '📄', 'name' => 'Lorem Ipsum Generator', 'desc' => 'Generate placeholder paragraphs.'],
    ['id' => 'remove-extra-spaces', 'cat' => 'text', 'icon' => '␣', 'name' => 'Whitespace Cleaner', 'desc' => 'Trim and collapse extra spaces and blank lines.'],
    ['id' => 'count-char-freq', 'cat' => 'text', 'icon' => '📊', 'name' => 'Character Frequency', 'desc' => 'Count how often each character appears.'],
    ['id' => 'text-to-slug', 'cat' => 'text', 'icon' => '🔗', 'name' => 'Slug Generator', 'desc' => 'Turn any title into a clean URL slug.'],
    ['id' => 'remove-line-breaks', 'cat' => 'text', 'icon' => '↩️', 'name' => 'Remove Line Breaks', 'desc' => 'Join wrapped lines into one paragraph.'],
    ['id' => 'add-line-numbers', 'cat' => 'text', 'icon' => '#️⃣', 'name' => 'Add Line Numbers', 'desc' => 'Prefix each line with its number.'],
    ['id' => 'text-stats-uniqueness', 'cat' => 'text', 'icon' => '🔤', 'name' => 'Unique Words', 'desc' => 'List and count unique words.'],
    ['id' => 'palindrome-check', 'cat' => 'text', 'icon' => '🔄', 'name' => 'Palindrome Checker', 'desc' => 'Check if text reads the same both ways.'],
    ['id' => 'rot13', 'cat' => 'text', 'icon' => '🔐', 'name' => 'ROT13 Cipher', 'desc' => 'Encode/decode with the classic ROT13.'],
    ['id' => 'morse-code', 'cat' => 'text', 'icon' => '📡', 'name' => 'Morse Code Translator', 'desc' => 'Convert text to/from Morse code.'],
    ['id' => 'binary-text', 'cat' => 'text', 'icon' => '💾', 'name' => 'Text ⇄ Binary', 'desc' => 'Convert text to binary and back.'],
    ['id' => 'text-truncate', 'cat' => 'text', 'icon' => '✂️', 'name' => 'Text Truncator', 'desc' => 'Cut text to a length with an ellipsis.'],
    ['id' => 'extract-emails', 'cat' => 'text', 'icon' => '📧', 'name' => 'Email Extractor', 'desc' => 'Pull all email addresses from text.'],
    ['id' => 'extract-urls', 'cat' => 'text', 'icon' => '🌐', 'name' => 'URL Extractor', 'desc' => 'Extract all links from a block of text.'],
    ['id' => 'text-to-html-list', 'cat' => 'text', 'icon' => '📋', 'name' => 'Lines → HTML List', 'desc' => 'Turn lines into a <ul> or <ol>.'],
    ['id' => 'nato-alphabet', 'cat' => 'text', 'icon' => '🎙️', 'name' => 'NATO Phonetic', 'desc' => 'Spell words with the NATO alphabet.'],
    ['id' => 'title-capitalizer', 'cat' => 'text', 'icon' => '🅰️', 'name' => 'Headline Capitalizer', 'desc' => 'Proper title-case ignoring small words.'],
    ['id' => 'percentage-calc', 'cat' => 'math', 'icon' => '％', 'name' => 'Percentage Calculator', 'desc' => 'What is X% of Y, and X is what % of Y.'],
    ['id' => 'avg-calc', 'cat' => 'math', 'icon' => '📈', 'name' => 'Average / Mean / Median', 'desc' => 'Statistics for a list of numbers.'],
    ['id' => 'tip-calc', 'cat' => 'math', 'icon' => '🧾', 'name' => 'Tip Calculator', 'desc' => 'Split a bill and tip between people.'],
    ['id' => 'discount-calc', 'cat' => 'math', 'icon' => '🏷️', 'name' => 'Discount Calculator', 'desc' => 'Final price after a percentage off.'],
    ['id' => 'loan-calc', 'cat' => 'math', 'icon' => '🏦', 'name' => 'Loan / EMI Calculator', 'desc' => 'Monthly payment for a loan.'],
    ['id' => 'bmi-calc', 'cat' => 'math', 'icon' => '⚖️', 'name' => 'BMI Calculator', 'desc' => 'Body Mass Index from height & weight.'],
    ['id' => 'age-calc', 'cat' => 'math', 'icon' => '🎂', 'name' => 'Age Calculator', 'desc' => 'Exact age in years, months and days.'],
    ['id' => 'random-number', 'cat' => 'math', 'icon' => '🎲', 'name' => 'Random Number Generator', 'desc' => 'Random integers in a range.'],
    ['id' => 'number-base', 'cat' => 'math', 'icon' => '🔢', 'name' => 'Number Base Converter', 'desc' => 'Convert between binary, octal, decimal, hex.'],
    ['id' => 'gcd-lcm', 'cat' => 'math', 'icon' => '➗', 'name' => 'GCD & LCM', 'desc' => 'Greatest common divisor and least common multiple.'],
    ['id' => 'prime-check', 'cat' => 'math', 'icon' => '🔎', 'name' => 'Prime Checker', 'desc' => 'Is a number prime? Plus its factors.'],
    ['id' => 'factorial', 'cat' => 'math', 'icon' => '❗', 'name' => 'Factorial Calculator', 'desc' => 'Compute n! for reasonable n.'],
    ['id' => 'fibonacci', 'cat' => 'math', 'icon' => '🌀', 'name' => 'Fibonacci Generator', 'desc' => 'First N Fibonacci numbers.'],
    ['id' => 'quadratic', 'cat' => 'math', 'icon' => '📐', 'name' => 'Quadratic Solver', 'desc' => 'Solve ax² + bx + c = 0.'],
    ['id' => 'temp-convert', 'cat' => 'math', 'icon' => '🌡️', 'name' => 'Temperature Converter', 'desc' => 'Celsius, Fahrenheit and Kelvin.'],
    ['id' => 'roman-numeral', 'cat' => 'math', 'icon' => 'Ⅹ', 'name' => 'Roman Numerals', 'desc' => 'Convert numbers to Roman and back.'],
    ['id' => 'scientific-notation', 'cat' => 'math', 'icon' => '🔬', 'name' => 'Scientific Notation', 'desc' => 'Convert to and from scientific notation.'],
    ['id' => 'ratio-simplify', 'cat' => 'math', 'icon' => '⚗️', 'name' => 'Ratio Simplifier', 'desc' => 'Reduce a ratio to lowest terms.'],
    ['id' => 'compound-interest', 'cat' => 'math', 'icon' => '💰', 'name' => 'Compound Interest', 'desc' => 'Grow savings with compound interest.'],
    ['id' => 'hex-rgb', 'cat' => 'color', 'icon' => '🎨', 'name' => 'HEX ⇄ RGB ⇄ HSL', 'desc' => 'Convert a color between all formats.'],
    ['id' => 'color-shades', 'cat' => 'color', 'icon' => '🌗', 'name' => 'Shade Generator', 'desc' => 'Generate lighter and darker shades.'],
    ['id' => 'color-contrast', 'cat' => 'color', 'icon' => '👁️', 'name' => 'Contrast Checker', 'desc' => 'WCAG contrast ratio between two colors.'],
    ['id' => 'complementary-color', 'cat' => 'color', 'icon' => '🌈', 'name' => 'Color Harmonies', 'desc' => 'Complementary, triadic and analogous colors.'],
    ['id' => 'gradient-generator', 'cat' => 'color', 'icon' => '🖌️', 'name' => 'CSS Gradient Maker', 'desc' => 'Build a linear-gradient and copy the CSS.'],
    ['id' => 'random-color', 'cat' => 'color', 'icon' => '🎰', 'name' => 'Random Color', 'desc' => 'Generate a random color palette.'],
    ['id' => 'rgba-hex', 'cat' => 'color', 'icon' => '🫧', 'name' => 'HEX + Alpha → RGBA', 'desc' => 'Add transparency to a hex color.'],
    ['id' => 'color-blindness', 'cat' => 'color', 'icon' => '🕶️', 'name' => 'Colorblind Simulator', 'desc' => 'Approximate how a color looks to colorblind users.'],
    ['id' => 'tailwind-shade', 'cat' => 'color', 'icon' => '📶', 'name' => 'Tailwind Scale', 'desc' => 'Generate a 50–900 scale from one color.'],
    ['id' => 'name-that-color', 'cat' => 'color', 'icon' => '🏷️', 'name' => 'Nearest Color Name', 'desc' => 'Find the closest named CSS color.'],
    ['id' => 'hsl-to-hex', 'cat' => 'color', 'icon' => '🎛️', 'name' => 'HSL → HEX', 'desc' => 'Convert HSL values to a hex color.'],
    ['id' => 'brightness-adjust', 'cat' => 'color', 'icon' => '🔆', 'name' => 'Brightness Adjuster', 'desc' => 'Lighten or darken a color by a percentage.'],
    ['id' => 'palette-from-image-hint', 'cat' => 'color', 'icon' => '🎨', 'name' => 'Brand Palette Builder', 'desc' => 'Build a 5-color palette around a hue.'],
    ['id' => 'css-shadow', 'cat' => 'color', 'icon' => '🌑', 'name' => 'Box-Shadow Generator', 'desc' => 'Design a CSS box-shadow and copy it.'],
    ['id' => 'json-formatter', 'cat' => 'dev', 'icon' => '{ }', 'name' => 'JSON Formatter', 'desc' => 'Pretty-print and validate JSON.'],
    ['id' => 'base64', 'cat' => 'dev', 'icon' => '🔡', 'name' => 'Base64 Encode/Decode', 'desc' => 'Encode or decode Base64 (UTF-8 safe).'],
    ['id' => 'url-encode', 'cat' => 'dev', 'icon' => '🔗', 'name' => 'URL Encode/Decode', 'desc' => 'Percent-encode or decode a URL component.'],
    ['id' => 'html-encode', 'cat' => 'dev', 'icon' => '⟨⟩', 'name' => 'HTML Entity Encoder', 'desc' => 'Escape or unescape HTML entities.'],
    ['id' => 'jwt-decode', 'cat' => 'dev', 'icon' => '🔓', 'name' => 'JWT Decoder', 'desc' => 'Decode a JWT header and payload (no verify).'],
    ['id' => 'uuid-gen', 'cat' => 'dev', 'icon' => '🆔', 'name' => 'UUID Generator', 'desc' => 'Generate v4 UUIDs.'],
    ['id' => 'hash-gen', 'cat' => 'dev', 'icon' => '#️⃣', 'name' => 'SHA Hash Generator', 'desc' => 'SHA-1, SHA-256, SHA-384, SHA-512.'],
    ['id' => 'color-hex-validate', 'cat' => 'dev', 'icon' => '⏱️', 'name' => 'Timestamp Converter', 'desc' => 'Unix timestamp ⇄ human date.'],
    ['id' => 'cron-explainer', 'cat' => 'dev', 'icon' => '⏰', 'name' => 'Cron Describer', 'desc' => 'Explain a 5-field cron expression.'],
    ['id' => 'regex-tester', 'cat' => 'dev', 'icon' => '🔣', 'name' => 'Regex Tester', 'desc' => 'Test a regex against text and see matches.'],
    ['id' => 'css-minify', 'cat' => 'dev', 'icon' => '📉', 'name' => 'CSS Minifier', 'desc' => 'Strip comments and whitespace from CSS.'],
    ['id' => 'js-minify', 'cat' => 'dev', 'icon' => '🧽', 'name' => 'JS Comment Stripper', 'desc' => 'Remove comments & extra whitespace from JS.'],
    ['id' => 'html-to-jsx', 'cat' => 'dev', 'icon' => '⚛️', 'name' => 'HTML → JSX', 'desc' => 'Convert HTML attributes to JSX.'],
    ['id' => 'query-string-parse', 'cat' => 'dev', 'icon' => '❓', 'name' => 'Query String Parser', 'desc' => 'Parse a URL query string into pairs.'],
    ['id' => 'json-to-csv', 'cat' => 'dev', 'icon' => '📑', 'name' => 'JSON → CSV', 'desc' => 'Flatten a JSON array into CSV.'],
    ['id' => 'csv-to-json', 'cat' => 'dev', 'icon' => '🗂️', 'name' => 'CSV → JSON', 'desc' => 'Turn CSV rows into JSON objects.'],
    ['id' => 'color-to-css-var', 'cat' => 'dev', 'icon' => '🌐', 'name' => 'HTTP Status Lookup', 'desc' => 'Explain any HTTP status code.'],
    ['id' => 'lorem-json', 'cat' => 'dev', 'icon' => '🧪', 'name' => 'Mock JSON Generator', 'desc' => 'Generate fake user records as JSON.'],
    ['id' => 'slugify-dev', 'cat' => 'dev', 'icon' => '🐍', 'name' => 'Variable Name Formatter', 'desc' => 'Format a phrase as camel/snake/pascal/const.'],
    ['id' => 'markdown-preview', 'cat' => 'dev', 'icon' => '📘', 'name' => 'Markdown → HTML', 'desc' => 'Convert basic Markdown to HTML.'],
    ['id' => 'ascii-table', 'cat' => 'dev', 'icon' => '🔤', 'name' => 'ASCII Lookup', 'desc' => 'Character ⇄ ASCII/Unicode code point.'],
    ['id' => 'string-escape', 'cat' => 'dev', 'icon' => '⌨️', 'name' => 'String Escaper', 'desc' => 'Escape a string for JSON / JS.'],
    ['id' => 'indent-converter', 'cat' => 'dev', 'icon' => '↹', 'name' => 'Tabs ⇄ Spaces', 'desc' => 'Convert indentation in code.'],
    ['id' => 'user-agent-parse', 'cat' => 'dev', 'icon' => '🖥️', 'name' => 'Your User-Agent', 'desc' => 'Show and parse your browser user-agent.'],
    ['id' => 'meta-tag-gen', 'cat' => 'seo', 'icon' => '🏷️', 'name' => 'Meta Tag Generator', 'desc' => 'Generate SEO + Open Graph meta tags.'],
    ['id' => 'serp-preview', 'cat' => 'seo', 'icon' => '🔍', 'name' => 'SERP Snippet Preview', 'desc' => 'Preview how your page looks in Google.'],
    ['id' => 'keyword-density', 'cat' => 'seo', 'icon' => '📊', 'name' => 'Keyword Density', 'desc' => 'Top keywords and their density.'],
    ['id' => 'robots-gen', 'cat' => 'seo', 'icon' => '🤖', 'name' => 'robots.txt Generator', 'desc' => 'Build a robots.txt file.'],
    ['id' => 'schema-gen', 'cat' => 'seo', 'icon' => '📋', 'name' => 'JSON-LD Schema', 'desc' => 'Generate Article/Organization schema.'],
    ['id' => 'utm-builder', 'cat' => 'seo', 'icon' => '🎯', 'name' => 'UTM Link Builder', 'desc' => 'Build campaign tracking URLs.'],
    ['id' => 'title-length', 'cat' => 'seo', 'icon' => '📏', 'name' => 'Title/Desc Length Checker', 'desc' => 'Check pixel-safe title & meta length.'],
    ['id' => 'og-preview', 'cat' => 'seo', 'icon' => '📱', 'name' => 'Social Card Preview', 'desc' => 'Preview an Open Graph share card.'],
    ['id' => 'hreflang-gen', 'cat' => 'seo', 'icon' => '🌍', 'name' => 'Hreflang Generator', 'desc' => 'Generate hreflang tags for languages.'],
    ['id' => 'sitemap-url-gen', 'cat' => 'seo', 'icon' => '🗺️', 'name' => 'Sitemap XML Builder', 'desc' => 'Build a sitemap from a list of URLs.'],
    ['id' => 'reading-level', 'cat' => 'seo', 'icon' => '📖', 'name' => 'Readability Score', 'desc' => 'Flesch reading-ease of your text.'],
    ['id' => 'canonical-gen', 'cat' => 'seo', 'icon' => '🔗', 'name' => 'Canonical Tag', 'desc' => 'Generate a canonical link tag.'],
    ['id' => 'twitter-card', 'cat' => 'seo', 'icon' => '🐦', 'name' => 'Twitter Card Tags', 'desc' => 'Generate Twitter card meta tags.'],
    ['id' => 'word-frequency-seo', 'cat' => 'seo', 'icon' => '📐', 'name' => 'Content Length Analyzer', 'desc' => 'Is your content long enough to rank?'],
    ['id' => 'anchor-text-gen', 'cat' => 'seo', 'icon' => '⚓', 'name' => 'Anchor Tag Builder', 'desc' => 'Build an SEO-friendly <a> tag.'],
    ['id' => 'redirect-gen', 'cat' => 'seo', 'icon' => '↪️', 'name' => '.htaccess Redirect', 'desc' => 'Generate a 301 redirect rule.'],
    ['id' => 'faq-schema', 'cat' => 'seo', 'icon' => '❔', 'name' => 'FAQ Schema Builder', 'desc' => 'Build FAQPage JSON-LD from Q&A.'],
    ['id' => 'breadcrumb-schema', 'cat' => 'seo', 'icon' => '🍞', 'name' => 'Breadcrumb Schema', 'desc' => 'Generate BreadcrumbList JSON-LD.'],
    ['id' => 'slug-seo', 'cat' => 'seo', 'icon' => '🌱', 'name' => 'SEO URL Slug', 'desc' => 'Clean, keyword-rich URL slug.'],
    ['id' => 'domain-age-hint', 'cat' => 'seo', 'icon' => '🖼️', 'name' => 'Alt Text Helper', 'desc' => 'Generate accessible image alt text tips.'],
    ['id' => 'password-gen', 'cat' => 'security', 'icon' => '🔑', 'name' => 'Password Generator', 'desc' => 'Strong random passwords.'],
    ['id' => 'password-strength', 'cat' => 'security', 'icon' => '🛡️', 'name' => 'Password Strength', 'desc' => 'Estimate password entropy and crack time.'],
    ['id' => 'pin-gen', 'cat' => 'security', 'icon' => '🔢', 'name' => 'PIN Generator', 'desc' => 'Random numeric PIN codes.'],
    ['id' => 'passphrase-gen', 'cat' => 'security', 'icon' => '📿', 'name' => 'Passphrase Generator', 'desc' => 'Memorable multi-word passphrases.'],
    ['id' => 'md5-note', 'cat' => 'security', 'icon' => '🖼️', 'name' => 'Base64 Image Encoder', 'desc' => 'Turn a small image into a data URI.'],
    ['id' => 'random-hex-token', 'cat' => 'security', 'icon' => '🎟️', 'name' => 'Secure Token', 'desc' => 'Cryptographically-random hex token.'],
    ['id' => 'htpasswd-note', 'cat' => 'security', 'icon' => '🔐', 'name' => 'Basic Auth Header', 'desc' => 'Build an HTTP Basic Auth header.'],
    ['id' => 'email-mask', 'cat' => 'security', 'icon' => '🕵️', 'name' => 'Email Masker', 'desc' => 'Partially hide an email for display.'],
    ['id' => 'credit-card-mask', 'cat' => 'security', 'icon' => '💳', 'name' => 'Card Number Masker', 'desc' => 'Mask all but the last 4 digits.'],
    ['id' => 'luhn-check', 'cat' => 'security', 'icon' => '✔️', 'name' => 'Luhn / Card Validator', 'desc' => 'Validate a card number checksum.'],
    ['id' => 'gdpr-cookie', 'cat' => 'security', 'icon' => '🍪', 'name' => 'Cookie Banner Snippet', 'desc' => 'Copy a simple consent banner.'],
    ['id' => 'ip-info', 'cat' => 'security', 'icon' => '📟', 'name' => 'What Is My Screen', 'desc' => 'Local browser & network info (private).'],
    ['id' => 'random-mac', 'cat' => 'security', 'icon' => '🔌', 'name' => 'Random MAC Address', 'desc' => 'Generate a random MAC address.'],
    ['id' => 'text-encrypt-xor', 'cat' => 'security', 'icon' => '🔀', 'name' => 'XOR Cipher', 'desc' => 'Simple XOR encrypt/decrypt with a key.'],
    ['id' => 'len-convert', 'cat' => 'convert', 'icon' => '📏', 'name' => 'Length Converter', 'desc' => 'Meters, feet, miles, km and more.'],
    ['id' => 'weight-convert', 'cat' => 'convert', 'icon' => '⚖️', 'name' => 'Weight Converter', 'desc' => 'Kg, lb, oz, tonnes and more.'],
    ['id' => 'volume-convert', 'cat' => 'convert', 'icon' => '🧪', 'name' => 'Volume Converter', 'desc' => 'Liters, gallons, cups and more.'],
    ['id' => 'area-convert', 'cat' => 'convert', 'icon' => '⬛', 'name' => 'Area Converter', 'desc' => 'm², ft², acres, hectares.'],
    ['id' => 'speed-convert', 'cat' => 'convert', 'icon' => '🏎️', 'name' => 'Speed Converter', 'desc' => 'km/h, mph, m/s, knots.'],
    ['id' => 'time-convert', 'cat' => 'convert', 'icon' => '⏳', 'name' => 'Time Converter', 'desc' => 'Seconds, minutes, hours, days.'],
    ['id' => 'data-convert', 'cat' => 'convert', 'icon' => '💽', 'name' => 'Data Size Converter', 'desc' => 'Bytes, KB, MB, GB, TB.'],
    ['id' => 'pressure-convert', 'cat' => 'convert', 'icon' => '🎈', 'name' => 'Pressure Converter', 'desc' => 'Pascal, bar, psi, atm.'],
    ['id' => 'energy-convert', 'cat' => 'convert', 'icon' => '⚡', 'name' => 'Energy Converter', 'desc' => 'Joule, calorie, kWh, BTU.'],
    ['id' => 'angle-convert', 'cat' => 'convert', 'icon' => '📐', 'name' => 'Angle Converter', 'desc' => 'Degrees, radians, gradians.'],
    ['id' => 'fuel-convert', 'cat' => 'convert', 'icon' => '⛽', 'name' => 'Fuel Economy', 'desc' => 'MPG, km/L, L/100km.'],
    ['id' => 'cooking-convert', 'cat' => 'convert', 'icon' => '🥄', 'name' => 'Cooking Measures', 'desc' => 'Tsp, tbsp, cup, mL.'],
    ['id' => 'digital-res', 'cat' => 'convert', 'icon' => '📻', 'name' => 'Frequency Converter', 'desc' => 'Hz, kHz, MHz, GHz.'],
    ['id' => 'power-convert', 'cat' => 'convert', 'icon' => '🔋', 'name' => 'Power Converter', 'desc' => 'Watts, kW, horsepower.'],
    ['id' => 'torque-convert', 'cat' => 'convert', 'icon' => '🔧', 'name' => 'Torque Converter', 'desc' => 'Nm, lb-ft, kg-m.'],
    ['id' => 'illuminance', 'cat' => 'convert', 'icon' => '💡', 'name' => 'Illuminance', 'desc' => 'Lux and foot-candles.'],
    ['id' => 'currency-note', 'cat' => 'convert', 'icon' => '🖼️', 'name' => 'Aspect Ratio Calculator', 'desc' => 'Compute missing width/height by ratio.'],
    ['id' => 'shoe-size', 'cat' => 'convert', 'icon' => '🔤', 'name' => 'Number to Words', 'desc' => 'Spell a number in English words.'],
    ['id' => 'base-n-convert', 'cat' => 'convert', 'icon' => '🔢', 'name' => 'Any Base Converter', 'desc' => 'Convert between base 2–36.'],
    ['id' => 'img-resize', 'cat' => 'image', 'icon' => '📐', 'name' => 'Image Resizer', 'desc' => 'Resize an image to a target width.'],
    ['id' => 'img-compress', 'cat' => 'image', 'icon' => '🗜️', 'name' => 'Image Compressor', 'desc' => 'Compress to JPEG at a quality level.'],
    ['id' => 'img-to-jpg', 'cat' => 'image', 'icon' => '🖼️', 'name' => 'PNG → JPG', 'desc' => 'Convert an image to JPEG.'],
    ['id' => 'img-to-png', 'cat' => 'image', 'icon' => '🏞️', 'name' => 'JPG → PNG', 'desc' => 'Convert an image to PNG.'],
    ['id' => 'img-to-webp', 'cat' => 'image', 'icon' => '🌐', 'name' => 'Convert to WebP', 'desc' => 'Export an image as WebP.'],
    ['id' => 'img-grayscale', 'cat' => 'image', 'icon' => '⬜', 'name' => 'Grayscale Filter', 'desc' => 'Convert an image to black & white.'],
    ['id' => 'img-invert', 'cat' => 'image', 'icon' => '🌗', 'name' => 'Invert Colors', 'desc' => 'Create a photo negative.'],
    ['id' => 'img-sepia', 'cat' => 'image', 'icon' => '🟫', 'name' => 'Sepia Filter', 'desc' => 'Apply a warm vintage tone.'],
    ['id' => 'img-rotate', 'cat' => 'image', 'icon' => '🔄', 'name' => 'Image Rotator', 'desc' => 'Rotate an image 90/180/270°.'],
    ['id' => 'img-flip', 'cat' => 'image', 'icon' => '🪞', 'name' => 'Image Flipper', 'desc' => 'Mirror horizontally or vertically.'],
    ['id' => 'img-crop-square', 'cat' => 'image', 'icon' => '⬛', 'name' => 'Square Crop', 'desc' => 'Center-crop to a square.'],
    ['id' => 'img-brightness', 'cat' => 'image', 'icon' => '🔆', 'name' => 'Brightness / Contrast', 'desc' => 'Adjust brightness of an image.'],
    ['id' => 'img-blur', 'cat' => 'image', 'icon' => '🌫️', 'name' => 'Blur Filter', 'desc' => 'Apply a Gaussian blur.'],
    ['id' => 'img-thumbnail', 'cat' => 'image', 'icon' => '🔲', 'name' => 'Thumbnail Maker', 'desc' => 'Create a small square thumbnail.'],
    ['id' => 'img-info', 'cat' => 'image', 'icon' => 'ℹ️', 'name' => 'Image Info', 'desc' => 'Show dimensions, ratio and size.'],
    ['id' => 'img-round', 'cat' => 'image', 'icon' => '🔘', 'name' => 'Rounded Corners', 'desc' => 'Add rounded corners (PNG).'],
    ['id' => 'img-watermark', 'cat' => 'image', 'icon' => '💧', 'name' => 'Text Watermark', 'desc' => 'Stamp text onto an image.'],
    ['id' => 'img-dominant', 'cat' => 'image', 'icon' => '🎨', 'name' => 'Dominant Color', 'desc' => 'Find the average color of an image.'],
    ['id' => 'img-pixelate', 'cat' => 'image', 'icon' => '🟦', 'name' => 'Pixelate', 'desc' => 'Apply a pixelation / mosaic effect.'],
    ['id' => 'img-favicon', 'cat' => 'image', 'icon' => '⭐', 'name' => 'Favicon Maker', 'desc' => 'Create a 32×32 favicon PNG.'],
    ['id' => 'countdown-days', 'cat' => 'product', 'icon' => '📅', 'name' => 'Days Until Date', 'desc' => 'Count days from today to any date.'],
    ['id' => 'date-diff', 'cat' => 'product', 'icon' => '📆', 'name' => 'Date Difference', 'desc' => 'Days/weeks between two dates.'],
    ['id' => 'add-days', 'cat' => 'product', 'icon' => '➕', 'name' => 'Add/Subtract Days', 'desc' => 'Find a date N days from a start.'],
    ['id' => 'time-zone-note', 'cat' => 'product', 'icon' => '🌏', 'name' => 'World Clock', 'desc' => 'Current time in major cities.'],
    ['id' => 'pomodoro-plan', 'cat' => 'product', 'icon' => '🍅', 'name' => 'Pomodoro Planner', 'desc' => 'Plan work/break cycles for a task.'],
    ['id' => 'reading-time-est', 'cat' => 'product', 'icon' => '⏲️', 'name' => 'Reading Time Estimator', 'desc' => 'How long to read this text.'],
    ['id' => 'grade-calc', 'cat' => 'product', 'icon' => '🎓', 'name' => 'Grade Calculator', 'desc' => 'Weighted average of your grades.'],
    ['id' => 'gpa-calc', 'cat' => 'product', 'icon' => '📚', 'name' => 'GPA Calculator', 'desc' => 'Compute GPA from grades & credits.'],
    ['id' => 'invoice-total', 'cat' => 'product', 'icon' => '🧾', 'name' => 'Invoice Total', 'desc' => 'Subtotal, tax and total for line items.'],
    ['id' => 'random-picker', 'cat' => 'product', 'icon' => '🏆', 'name' => 'Random Picker', 'desc' => 'Pick a random winner from a list.'],
    ['id' => 'list-shuffle', 'cat' => 'product', 'icon' => '🔀', 'name' => 'List Shuffler', 'desc' => 'Randomize the order of a list.'],
    ['id' => 'team-splitter', 'cat' => 'product', 'icon' => '👥', 'name' => 'Team Splitter', 'desc' => 'Split names into balanced teams.'],
    ['id' => 'dice-roll', 'cat' => 'product', 'icon' => '🎲', 'name' => 'Dice Roller', 'desc' => 'Roll dice (e.g. 2d6, 1d20).'],
    ['id' => 'coin-flip', 'cat' => 'product', 'icon' => '🪙', 'name' => 'Coin Flipper', 'desc' => 'Flip one or many coins.'],
    ['id' => 'countdown-timer-note', 'cat' => 'product', 'icon' => '💼', 'name' => 'Working Days Counter', 'desc' => 'Count business days between dates.'],
    ['id' => 'savings-goal', 'cat' => 'product', 'icon' => '🎯', 'name' => 'Savings Goal Planner', 'desc' => 'Monthly saving to reach a goal.'],
    ['id' => 'unit-price', 'cat' => 'product', 'icon' => '🛒', 'name' => 'Unit Price Compare', 'desc' => 'Which package is cheaper per unit?'],
    ['id' => 'hours-calc', 'cat' => 'product', 'icon' => '🕐', 'name' => 'Hours Calculator', 'desc' => 'Total hours between start & end time.'],
    ['id' => 'random-name', 'cat' => 'product', 'icon' => '🙂', 'name' => 'Username Generator', 'desc' => 'Generate available-looking usernames.'],
    ['id' => 'hashtag-gen', 'cat' => 'social', 'icon' => '#️⃣', 'name' => 'Hashtag Generator', 'desc' => 'Turn keywords into hashtags.'],
    ['id' => 'char-counter-social', 'cat' => 'social', 'icon' => '📱', 'name' => 'Social Char Counter', 'desc' => 'Character limits for each platform.'],
    ['id' => 'emoji-picker', 'cat' => 'social', 'icon' => '😀', 'name' => 'Emoji Search', 'desc' => 'Find emojis by keyword.'],
    ['id' => 'bio-gen', 'cat' => 'social', 'icon' => '📝', 'name' => 'Bio Formatter', 'desc' => 'Format a stylish multi-line bio.'],
    ['id' => 'tweet-splitter', 'cat' => 'social', 'icon' => '🧵', 'name' => 'Thread Splitter', 'desc' => 'Split long text into tweet-sized parts.'],
    ['id' => 'yt-title-score', 'cat' => 'social', 'icon' => '📰', 'name' => 'Headline Analyzer', 'desc' => 'Score a headline for engagement.'],
    ['id' => 'cta-gen', 'cat' => 'social', 'icon' => '📣', 'name' => 'CTA Generator', 'desc' => 'Get call-to-action phrase ideas.'],
    ['id' => 'fake-tweet-note', 'cat' => 'social', 'icon' => '🖼️', 'name' => 'Caption Length Splitter', 'desc' => 'Chunk captions for carousels.'],
    ['id' => 'engagement-rate', 'cat' => 'social', 'icon' => '📈', 'name' => 'Engagement Rate', 'desc' => 'Compute engagement rate %.'],
    ['id' => 'best-time-note', 'cat' => 'social', 'icon' => '☁️', 'name' => 'Word Cloud Data', 'desc' => 'Top words for a word-cloud.'],
    ['id' => 'poll-gen', 'cat' => 'social', 'icon' => '📊', 'name' => 'Poll Idea Formatter', 'desc' => 'Format a poll with options.'],
    ['id' => 'link-in-bio', 'cat' => 'social', 'icon' => '🔗', 'name' => 'Link-in-Bio Builder', 'desc' => 'Build a tidy link list block.'],
    ['id' => 'mention-extract', 'cat' => 'social', 'icon' => '@', 'name' => 'Mention & Tag Extractor', 'desc' => 'Pull @mentions and #hashtags.'],
    ['id' => 'emoji-remove', 'cat' => 'social', 'icon' => '🚫', 'name' => 'Emoji Remover', 'desc' => 'Strip all emojis from text.'],
    ['id' => 'title-emoji', 'cat' => 'social', 'icon' => '✨', 'name' => 'Emoji Title Enhancer', 'desc' => 'Add relevant emojis to a title.'],
    ['id' => 'aspect-social', 'cat' => 'social', 'icon' => '📐', 'name' => 'Social Image Sizes', 'desc' => 'Recommended image sizes per platform.'],
    ['id' => 'quote-card-note', 'cat' => 'social', 'icon' => '❝', 'name' => 'Quote Formatter', 'desc' => 'Format a quote card text.'],
    ['id' => 'follower-milestone', 'cat' => 'social', 'icon' => '🚀', 'name' => 'Growth Forecaster', 'desc' => 'Project follower growth over time.'],
    ['id' => 'ab-test-note', 'cat' => 'social', 'icon' => '🆚', 'name' => 'A/B Winner Calculator', 'desc' => 'Which variant has a better rate?'],
    ['id' => 'roi-calc', 'cat' => 'social', 'icon' => '💵', 'name' => 'Ad ROI Calculator', 'desc' => 'Return on ad spend and profit.'],
    ['id' => 'text-diff', 'cat' => 'text', 'icon' => '⚖️', 'name' => 'Text Diff', 'desc' => 'Show lines that differ between two texts.'],
    ['id' => 'acronym-gen', 'cat' => 'text', 'icon' => '🔡', 'name' => 'Acronym Maker', 'desc' => 'Build an acronym from a phrase.'],
    ['id' => 'pythagoras', 'cat' => 'math', 'icon' => '📐', 'name' => 'Pythagorean Theorem', 'desc' => 'Find the hypotenuse or a missing side.'],
    ['id' => 'string-to-color', 'cat' => 'dev', 'icon' => '🎨', 'name' => 'String → Color', 'desc' => 'Deterministic color from any string.'],
    ['id' => 'yes-no', 'cat' => 'product', 'icon' => '🎱', 'name' => 'Decision Maker', 'desc' => 'Let fate decide: yes or no.'],
    ['id' => 'download-time', 'cat' => 'convert', 'icon' => '📥', 'name' => 'Download Time', 'desc' => 'Estimate download time for a file.'],
    ['id' => 'text-entropy', 'cat' => 'security', 'icon' => '📉', 'name' => 'Text Entropy', 'desc' => 'Shannon entropy of a string (randomness).'],
    ['id' => 'initials-avatar', 'cat' => 'social', 'icon' => '🅰️', 'name' => 'Initials Avatar', 'desc' => 'Generate a colored initials avatar.'],
  ];
}
